inherit_from: ./ruby-2.3.yml

AllCops:
  TargetRubyVersion: 2.2

Layout:
  HeredocIndentation:
    Enabled: false

Performance/ConcurrentMonotonicTime:
  Enabled: false

# The foo&.bar syntax is not available until Ruby 2.3.
Style/SafeNavigation:
  Enabled: false
